server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}

neokod:
  postman:
    parse:
      filePath: /home/htemucin/einsan/postmans/2022_09_29_EInsanLogServer.postman_collection_v2.json
      #selectedItems:
      #  - authentication
      #  - user
      #  - user-register
    environment:
      filePath: /home/htemucin/einsan/postmans/einsan-test-dev.postman_environment.json
      variable:
        - baseUrl | api.einsan.org
        - KK_API_URL | https://api.einsan.org/kk
        - YTNK_API_URL | https://api.einsan.org/ytnk
    export:
      responseSelection: SUCCESS_ONLY
      basePath: /home/htemucin/einsan/request-response/einsan-log
      fileNameSeparator: _
      exportResponseHeader: false
      useResponseNameInFile: false
      baseDirectoryExistPolicy: delete
    request:
      header:
        - Host | apitest.einsan.org
        - Accept | application/json
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  jackson:
    serialization:
      fail-on-empty-beans: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      unwrap-root-value: false
  info:
  app:
    name: ${spring.application.name}
    description: ${SERVER_DESCRIPTION:Datalog Spring Demo Server}
  build:
    groupId: ${SERVER_BUILD_GROUP_ID:com.datalog}
    artifact: ${SERVER_BUILD_ARTIFACT:spring-demo-server}
    name: ${SERVER_BUILD_NAME:Datalog Server Project}
    version: ${SERVER_BUILD_VERSION:${module.version}